"""add_file_content_column

Revision ID: add_file_content_column
Revises: 3d0a9f2a7b1c
Create Date: 2026-03-12 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_file_content_column'
down_revision = '3d0a9f2a7b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_file', sa.Column('file_content', sa.LargeBinary(), nullable=True, comment='文件二进制内容（用于数据库存储模式）'))
    op.alter_column('sys_file', 'upload_type',
               existing_type=sa.VARCHAR(length=20),
               comment='上传类型（local/oss/database）',
               existing_comment='上传类型（local/oss）',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_file', 'upload_type',
               existing_type=sa.VARCHAR(length=20),
               comment='上传类型（local/oss）',
               existing_comment='上传类型（local/oss/database）',
               existing_nullable=False)
    op.drop_column('sys_file', 'file_content')
    # ### end Alembic commands ###